// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

package com.api.login3;

public final class LoginMessage {
  private LoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string passwd = 2;</code>
     */
    boolean hasPasswd();
    /**
     * <code>optional string passwd = 2;</code>
     */
    java.lang.String getPasswd();
    /**
     * <code>optional string passwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();

    /**
     * <code>repeated string phones = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getPhonesList();
    /**
     * <code>repeated string phones = 3;</code>
     */
    int getPhonesCount();
    /**
     * <code>repeated string phones = 3;</code>
     */
    java.lang.String getPhones(int index);
    /**
     * <code>repeated string phones = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);
  }
  /**
   * Protobuf type {@code MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MyMessage)
      MyMessageOrBuilder {
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyMessage defaultInstance;
    public static MyMessage getDefaultInstance() {
      return defaultInstance;
    }

    public MyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.login3.LoginMessage.internal_static_MyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.login3.LoginMessage.internal_static_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.login3.LoginMessage.MyMessage.class, com.api.login3.LoginMessage.MyMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<MyMessage> PARSER =
        new com.google.protobuf.AbstractParser<MyMessage>() {
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PASSWD_FIELD_NUMBER = 2;
    private java.lang.Object passwd_;
    /**
     * <code>optional string passwd = 2;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string passwd = 2;</code>
     */
    public java.lang.String getPasswd() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string passwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList phones_;
    /**
     * <code>repeated string phones = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated string phones = 3;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated string phones = 3;</code>
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated string phones = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    private void initFields() {
      id_ = 0L;
      passwd_ = "";
      phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.api.login3.LoginMessage.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.api.login3.LoginMessage.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.api.login3.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.api.login3.LoginMessage.MyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMessage)
        com.api.login3.LoginMessage.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.api.login3.LoginMessage.internal_static_MyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.api.login3.LoginMessage.internal_static_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.api.login3.LoginMessage.MyMessage.class, com.api.login3.LoginMessage.MyMessage.Builder.class);
      }

      // Construct using com.api.login3.LoginMessage.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.api.login3.LoginMessage.internal_static_MyMessage_descriptor;
      }

      public com.api.login3.LoginMessage.MyMessage getDefaultInstanceForType() {
        return com.api.login3.LoginMessage.MyMessage.getDefaultInstance();
      }

      public com.api.login3.LoginMessage.MyMessage build() {
        com.api.login3.LoginMessage.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.api.login3.LoginMessage.MyMessage buildPartial() {
        com.api.login3.LoginMessage.MyMessage result = new com.api.login3.LoginMessage.MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passwd_ = passwd_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = phones_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.phones_ = phones_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object passwd_ = "";
      /**
       * <code>optional string passwd = 2;</code>
       */
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public java.lang.String getPasswd() {
        java.lang.Object ref = passwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            passwd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        java.lang.Object ref = passwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder setPasswd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passwd_ = getDefaultInstance().getPasswd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        return phones_.getUnmodifiableView();
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder clearPhones() {
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyMessage)
    }

    static {
      defaultInstance = new MyMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MyMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MyMessage.proto\"7\n\tMyMessage\022\n\n\002id\030\001 \001" +
      "(\003\022\016\n\006passwd\030\002 \001(\t\022\016\n\006phones\030\003 \003(\tB \n\016co" +
      "m.api.login3B\014LoginMessageH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MyMessage_descriptor,
        new java.lang.String[] { "Id", "Passwd", "Phones", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
