/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.compare.thriftfile;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import javax.annotation.Generated;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-4-19")
public class HelloConDecode implements org.apache.thrift.TBase<HelloConDecode, HelloConDecode._Fields>, java.io.Serializable, Cloneable, Comparable<HelloConDecode> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HelloConDecode");

  private static final org.apache.thrift.protocol.TField HELLODECODE_FIELD_DESC = new org.apache.thrift.protocol.TField("hellodecode", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HelloConDecodeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HelloConDecodeTupleSchemeFactory());
  }

  public List<HelloTestDecode> hellodecode; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HELLODECODE((short)1, "hellodecode");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HELLODECODE
          return HELLODECODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.HELLODECODE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HELLODECODE, new org.apache.thrift.meta_data.FieldMetaData("hellodecode", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HelloTestDecode.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HelloConDecode.class, metaDataMap);
  }

  public HelloConDecode() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HelloConDecode(HelloConDecode other) {
    if (other.isSetHellodecode()) {
      List<HelloTestDecode> __this__hellodecode = new ArrayList<HelloTestDecode>(other.hellodecode.size());
      for (HelloTestDecode other_element : other.hellodecode) {
        __this__hellodecode.add(new HelloTestDecode(other_element));
      }
      this.hellodecode = __this__hellodecode;
    }
  }

  public HelloConDecode deepCopy() {
    return new HelloConDecode(this);
  }

  @Override
  public void clear() {
    this.hellodecode = null;
  }

  public int getHellodecodeSize() {
    return (this.hellodecode == null) ? 0 : this.hellodecode.size();
  }

  public java.util.Iterator<HelloTestDecode> getHellodecodeIterator() {
    return (this.hellodecode == null) ? null : this.hellodecode.iterator();
  }

  public void addToHellodecode(HelloTestDecode elem) {
    if (this.hellodecode == null) {
      this.hellodecode = new ArrayList<HelloTestDecode>();
    }
    this.hellodecode.add(elem);
  }

  public List<HelloTestDecode> getHellodecode() {
    return this.hellodecode;
  }

  public HelloConDecode setHellodecode(List<HelloTestDecode> hellodecode) {
    this.hellodecode = hellodecode;
    return this;
  }

  public void unsetHellodecode() {
    this.hellodecode = null;
  }

  /** Returns true if field hellodecode is set (has been assigned a value) and false otherwise */
  public boolean isSetHellodecode() {
    return this.hellodecode != null;
  }

  public void setHellodecodeIsSet(boolean value) {
    if (!value) {
      this.hellodecode = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HELLODECODE:
      if (value == null) {
        unsetHellodecode();
      } else {
        setHellodecode((List<HelloTestDecode>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HELLODECODE:
      return getHellodecode();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HELLODECODE:
      return isSetHellodecode();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HelloConDecode)
      return this.equals((HelloConDecode)that);
    return false;
  }

  public boolean equals(HelloConDecode that) {
    if (that == null)
      return false;

    boolean this_present_hellodecode = true && this.isSetHellodecode();
    boolean that_present_hellodecode = true && that.isSetHellodecode();
    if (this_present_hellodecode || that_present_hellodecode) {
      if (!(this_present_hellodecode && that_present_hellodecode))
        return false;
      if (!this.hellodecode.equals(that.hellodecode))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_hellodecode = true && (isSetHellodecode());
    list.add(present_hellodecode);
    if (present_hellodecode)
      list.add(hellodecode);

    return list.hashCode();
  }

  @Override
  public int compareTo(HelloConDecode other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHellodecode()).compareTo(other.isSetHellodecode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHellodecode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hellodecode, other.hellodecode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HelloConDecode(");
    boolean first = true;

    if (isSetHellodecode()) {
      sb.append("hellodecode:");
      if (this.hellodecode == null) {
        sb.append("null");
      } else {
        sb.append(this.hellodecode);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HelloConDecodeStandardSchemeFactory implements SchemeFactory {
    public HelloConDecodeStandardScheme getScheme() {
      return new HelloConDecodeStandardScheme();
    }
  }

  private static class HelloConDecodeStandardScheme extends StandardScheme<HelloConDecode> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HelloConDecode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HELLODECODE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.hellodecode = new ArrayList<HelloTestDecode>(_list8.size);
                HelloTestDecode _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new HelloTestDecode();
                  _elem9.read(iprot);
                  struct.hellodecode.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setHellodecodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HelloConDecode struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.hellodecode != null) {
        if (struct.isSetHellodecode()) {
          oprot.writeFieldBegin(HELLODECODE_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.hellodecode.size()));
            for (HelloTestDecode _iter11 : struct.hellodecode)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HelloConDecodeTupleSchemeFactory implements SchemeFactory {
    public HelloConDecodeTupleScheme getScheme() {
      return new HelloConDecodeTupleScheme();
    }
  }

  private static class HelloConDecodeTupleScheme extends TupleScheme<HelloConDecode> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HelloConDecode struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetHellodecode()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetHellodecode()) {
        {
          oprot.writeI32(struct.hellodecode.size());
          for (HelloTestDecode _iter12 : struct.hellodecode)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HelloConDecode struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.hellodecode = new ArrayList<HelloTestDecode>(_list13.size);
          HelloTestDecode _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new HelloTestDecode();
            _elem14.read(iprot);
            struct.hellodecode.add(_elem14);
          }
        }
        struct.setHellodecodeIsSet(true);
      }
    }
  }

}

