// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

package com.api.login2;

public final class LoginMessage {
  private LoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string passwd = 2;</code>
     */
    boolean hasPasswd();
    /**
     * <code>optional string passwd = 2;</code>
     */
    java.lang.String getPasswd();
    /**
     * <code>optional string passwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();

    /**
     * <code>repeated string phones = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getPhonesList();
    /**
     * <code>repeated string phones = 3;</code>
     */
    int getPhonesCount();
    /**
     * <code>repeated string phones = 3;</code>
     */
    java.lang.String getPhones(int index);
    /**
     * <code>repeated string phones = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);
  }
  /**
   * Protobuf type {@code MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:MyMessage)
      MyMessageOrBuilder {
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyMessage(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final MyMessage defaultInstance;
    public static MyMessage getDefaultInstance() {
      return defaultInstance;
    }

    public MyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              passwd_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                phones_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              phones_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = phones_.getUnmodifiableView();
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<MyMessage> PARSER =
        new com.google.protobuf.AbstractParser<MyMessage>() {
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PASSWD_FIELD_NUMBER = 2;
    private java.lang.Object passwd_;
    /**
     * <code>optional string passwd = 2;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string passwd = 2;</code>
     */
    public java.lang.String getPasswd() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string passwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList phones_;
    /**
     * <code>repeated string phones = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated string phones = 3;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated string phones = 3;</code>
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated string phones = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    private void initFields() {
      id_ = 0L;
      passwd_ = "";
      phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswdBytes());
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeBytes(3, phones_.getByteString(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phones_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(phones_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPhonesList().size();
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.api.login2.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.api.login2.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.api.login2.LoginMessage.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.api.login2.LoginMessage.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.api.login2.LoginMessage.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.api.login2.LoginMessage.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.api.login2.LoginMessage.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.api.login2.LoginMessage.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.api.login2.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.api.login2.LoginMessage.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.api.login2.LoginMessage.MyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.api.login2.LoginMessage.MyMessage, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:MyMessage)
        com.api.login2.LoginMessage.MyMessageOrBuilder {
      // Construct using com.api.login2.LoginMessage.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.api.login2.LoginMessage.MyMessage getDefaultInstanceForType() {
        return com.api.login2.LoginMessage.MyMessage.getDefaultInstance();
      }

      public com.api.login2.LoginMessage.MyMessage build() {
        com.api.login2.LoginMessage.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.api.login2.LoginMessage.MyMessage buildPartial() {
        com.api.login2.LoginMessage.MyMessage result = new com.api.login2.LoginMessage.MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passwd_ = passwd_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = phones_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.phones_ = phones_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.api.login2.LoginMessage.MyMessage other) {
        if (other == com.api.login2.LoginMessage.MyMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPasswd()) {
          bitField0_ |= 0x00000002;
          passwd_ = other.passwd_;
          
        }
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.api.login2.LoginMessage.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.api.login2.LoginMessage.MyMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        
        return this;
      }

      private java.lang.Object passwd_ = "";
      /**
       * <code>optional string passwd = 2;</code>
       */
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public java.lang.String getPasswd() {
        java.lang.Object ref = passwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            passwd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        java.lang.Object ref = passwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder setPasswd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        
        return this;
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passwd_ = getDefaultInstance().getPasswd();
        
        return this;
      }
      /**
       * <code>optional string passwd = 2;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passwd_ = value;
        
        return this;
      }

      private com.google.protobuf.LazyStringList phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        return phones_.getUnmodifiableView();
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder clearPhones() {
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      /**
       * <code>repeated string phones = 3;</code>
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyMessage)
    }

    static {
      defaultInstance = new MyMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MyMessage)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
