// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testcompare.proto

package com.compare.protobuffile;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HelloTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.compare.HelloTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2 [default = "default"];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = "default"];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2 [default = "default"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string speak = 3;</code>
     */
    boolean hasSpeak();
    /**
     * <code>optional string speak = 3;</code>
     */
    java.lang.String getSpeak();
    /**
     * <code>optional string speak = 3;</code>
     */
    com.google.protobuf.ByteString
        getSpeakBytes();

    /**
     * <code>repeated string phone = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getPhoneList();
    /**
     * <code>repeated string phone = 4;</code>
     */
    int getPhoneCount();
    /**
     * <code>repeated string phone = 4;</code>
     */
    java.lang.String getPhone(int index);
    /**
     * <code>repeated string phone = 4;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes(int index);
  }
  /**
   * Protobuf type {@code com.compare.HelloTest}
   */
  public static final class HelloTest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.compare.HelloTest)
      HelloTestOrBuilder {
    // Use HelloTest.newBuilder() to construct.
    private HelloTest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloTest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloTest defaultInstance;
    public static HelloTest getDefaultInstance() {
      return defaultInstance;
    }

    public HelloTest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              speak_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                phone_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              phone_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = phone_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.compare.protobuffile.Test.internal_static_com_compare_HelloTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.compare.protobuffile.Test.internal_static_com_compare_HelloTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.compare.protobuffile.Test.HelloTest.class, com.compare.protobuffile.Test.HelloTest.Builder.class);
    }

    public static com.google.protobuf.Parser<HelloTest> PARSER =
        new com.google.protobuf.AbstractParser<HelloTest>() {
      public HelloTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloTest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HelloTest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2 [default = "default"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2 [default = "default"];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = "default"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPEAK_FIELD_NUMBER = 3;
    private java.lang.Object speak_;
    /**
     * <code>optional string speak = 3;</code>
     */
    public boolean hasSpeak() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string speak = 3;</code>
     */
    public java.lang.String getSpeak() {
      java.lang.Object ref = speak_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          speak_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string speak = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSpeakBytes() {
      java.lang.Object ref = speak_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        speak_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList phone_;
    /**
     * <code>repeated string phone = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated string phone = 4;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated string phone = 4;</code>
     */
    public java.lang.String getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated string phone = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes(int index) {
      return phone_.getByteString(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "default";
      speak_ = "";
      phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSpeakBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeBytes(4, phone_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSpeakBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phone_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(phone_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPhoneList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.compare.protobuffile.Test.HelloTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.compare.protobuffile.Test.HelloTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.compare.protobuffile.Test.HelloTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.compare.protobuffile.Test.HelloTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.compare.protobuffile.Test.HelloTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.compare.protobuffile.Test.HelloTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.compare.protobuffile.Test.HelloTest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.compare.HelloTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.compare.HelloTest)
        com.compare.protobuffile.Test.HelloTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.compare.protobuffile.Test.internal_static_com_compare_HelloTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.compare.protobuffile.Test.internal_static_com_compare_HelloTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.compare.protobuffile.Test.HelloTest.class, com.compare.protobuffile.Test.HelloTest.Builder.class);
      }

      // Construct using com.compare.protobuffile.Test.HelloTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "default";
        bitField0_ = (bitField0_ & ~0x00000002);
        speak_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.compare.protobuffile.Test.internal_static_com_compare_HelloTest_descriptor;
      }

      public com.compare.protobuffile.Test.HelloTest getDefaultInstanceForType() {
        return com.compare.protobuffile.Test.HelloTest.getDefaultInstance();
      }

      public com.compare.protobuffile.Test.HelloTest build() {
        com.compare.protobuffile.Test.HelloTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.compare.protobuffile.Test.HelloTest buildPartial() {
        com.compare.protobuffile.Test.HelloTest result = new com.compare.protobuffile.Test.HelloTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.speak_ = speak_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = phone_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.compare.protobuffile.Test.HelloTest) {
          return mergeFrom((com.compare.protobuffile.Test.HelloTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.compare.protobuffile.Test.HelloTest other) {
        if (other == com.compare.protobuffile.Test.HelloTest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSpeak()) {
          bitField0_ |= 0x00000004;
          speak_ = other.speak_;
          onChanged();
        }
        if (!other.phone_.isEmpty()) {
          if (phone_.isEmpty()) {
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhoneIsMutable();
            phone_.addAll(other.phone_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.compare.protobuffile.Test.HelloTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.compare.protobuffile.Test.HelloTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "default";
      /**
       * <code>optional string name = 2 [default = "default"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2 [default = "default"];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "default"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "default"];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "default"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "default"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object speak_ = "";
      /**
       * <code>optional string speak = 3;</code>
       */
      public boolean hasSpeak() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string speak = 3;</code>
       */
      public java.lang.String getSpeak() {
        java.lang.Object ref = speak_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            speak_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string speak = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSpeakBytes() {
        java.lang.Object ref = speak_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          speak_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string speak = 3;</code>
       */
      public Builder setSpeak(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        speak_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string speak = 3;</code>
       */
      public Builder clearSpeak() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speak_ = getDefaultInstance().getSpeak();
        onChanged();
        return this;
      }
      /**
       * <code>optional string speak = 3;</code>
       */
      public Builder setSpeakBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        speak_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = new com.google.protobuf.LazyStringArrayList(phone_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhoneList() {
        return phone_.getUnmodifiableView();
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public int getPhoneCount() {
        return phone_.size();
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public java.lang.String getPhone(int index) {
        return phone_.get(index);
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes(int index) {
        return phone_.getByteString(index);
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public Builder setPhone(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
        phone_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public Builder addPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
        phone_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhoneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phone_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public Builder clearPhone() {
        phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       */
      public Builder addPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
        phone_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.compare.HelloTest)
    }

    static {
      defaultInstance = new HelloTest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.compare.HelloTest)
  }

  public interface HelloConOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.compare.HelloCon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    java.util.List<com.compare.protobuffile.Test.HelloTest> 
        getHelloList();
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    com.compare.protobuffile.Test.HelloTest getHello(int index);
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    int getHelloCount();
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    java.util.List<? extends com.compare.protobuffile.Test.HelloTestOrBuilder> 
        getHelloOrBuilderList();
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    com.compare.protobuffile.Test.HelloTestOrBuilder getHelloOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.compare.HelloCon}
   */
  public static final class HelloCon extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.compare.HelloCon)
      HelloConOrBuilder {
    // Use HelloCon.newBuilder() to construct.
    private HelloCon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloCon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloCon defaultInstance;
    public static HelloCon getDefaultInstance() {
      return defaultInstance;
    }

    public HelloCon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloCon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                hello_ = new java.util.ArrayList<com.compare.protobuffile.Test.HelloTest>();
                mutable_bitField0_ |= 0x00000001;
              }
              hello_.add(input.readMessage(com.compare.protobuffile.Test.HelloTest.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          hello_ = java.util.Collections.unmodifiableList(hello_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.compare.protobuffile.Test.internal_static_com_compare_HelloCon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.compare.protobuffile.Test.internal_static_com_compare_HelloCon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.compare.protobuffile.Test.HelloCon.class, com.compare.protobuffile.Test.HelloCon.Builder.class);
    }

    public static com.google.protobuf.Parser<HelloCon> PARSER =
        new com.google.protobuf.AbstractParser<HelloCon>() {
      public HelloCon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloCon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HelloCon> getParserForType() {
      return PARSER;
    }

    public static final int HELLO_FIELD_NUMBER = 1;
    private java.util.List<com.compare.protobuffile.Test.HelloTest> hello_;
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    public java.util.List<com.compare.protobuffile.Test.HelloTest> getHelloList() {
      return hello_;
    }
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    public java.util.List<? extends com.compare.protobuffile.Test.HelloTestOrBuilder> 
        getHelloOrBuilderList() {
      return hello_;
    }
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    public int getHelloCount() {
      return hello_.size();
    }
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    public com.compare.protobuffile.Test.HelloTest getHello(int index) {
      return hello_.get(index);
    }
    /**
     * <code>repeated .com.compare.HelloTest hello = 1;</code>
     */
    public com.compare.protobuffile.Test.HelloTestOrBuilder getHelloOrBuilder(
        int index) {
      return hello_.get(index);
    }

    private void initFields() {
      hello_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getHelloCount(); i++) {
        if (!getHello(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < hello_.size(); i++) {
        output.writeMessage(1, hello_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hello_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hello_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.compare.protobuffile.Test.HelloCon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.compare.protobuffile.Test.HelloCon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloCon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.compare.protobuffile.Test.HelloCon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloCon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.compare.protobuffile.Test.HelloCon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloCon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.compare.protobuffile.Test.HelloCon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.compare.protobuffile.Test.HelloCon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.compare.protobuffile.Test.HelloCon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.compare.protobuffile.Test.HelloCon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.compare.HelloCon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.compare.HelloCon)
        com.compare.protobuffile.Test.HelloConOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.compare.protobuffile.Test.internal_static_com_compare_HelloCon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.compare.protobuffile.Test.internal_static_com_compare_HelloCon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.compare.protobuffile.Test.HelloCon.class, com.compare.protobuffile.Test.HelloCon.Builder.class);
      }

      // Construct using com.compare.protobuffile.Test.HelloCon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHelloFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (helloBuilder_ == null) {
          hello_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          helloBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.compare.protobuffile.Test.internal_static_com_compare_HelloCon_descriptor;
      }

      public com.compare.protobuffile.Test.HelloCon getDefaultInstanceForType() {
        return com.compare.protobuffile.Test.HelloCon.getDefaultInstance();
      }

      public com.compare.protobuffile.Test.HelloCon build() {
        com.compare.protobuffile.Test.HelloCon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.compare.protobuffile.Test.HelloCon buildPartial() {
        com.compare.protobuffile.Test.HelloCon result = new com.compare.protobuffile.Test.HelloCon(this);
        int from_bitField0_ = bitField0_;
        if (helloBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            hello_ = java.util.Collections.unmodifiableList(hello_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hello_ = hello_;
        } else {
          result.hello_ = helloBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.compare.protobuffile.Test.HelloCon) {
          return mergeFrom((com.compare.protobuffile.Test.HelloCon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.compare.protobuffile.Test.HelloCon other) {
        if (other == com.compare.protobuffile.Test.HelloCon.getDefaultInstance()) return this;
        if (helloBuilder_ == null) {
          if (!other.hello_.isEmpty()) {
            if (hello_.isEmpty()) {
              hello_ = other.hello_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHelloIsMutable();
              hello_.addAll(other.hello_);
            }
            onChanged();
          }
        } else {
          if (!other.hello_.isEmpty()) {
            if (helloBuilder_.isEmpty()) {
              helloBuilder_.dispose();
              helloBuilder_ = null;
              hello_ = other.hello_;
              bitField0_ = (bitField0_ & ~0x00000001);
              helloBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHelloFieldBuilder() : null;
            } else {
              helloBuilder_.addAllMessages(other.hello_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getHelloCount(); i++) {
          if (!getHello(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.compare.protobuffile.Test.HelloCon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.compare.protobuffile.Test.HelloCon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.compare.protobuffile.Test.HelloTest> hello_ =
        java.util.Collections.emptyList();
      private void ensureHelloIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          hello_ = new java.util.ArrayList<com.compare.protobuffile.Test.HelloTest>(hello_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.compare.protobuffile.Test.HelloTest, com.compare.protobuffile.Test.HelloTest.Builder, com.compare.protobuffile.Test.HelloTestOrBuilder> helloBuilder_;

      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public java.util.List<com.compare.protobuffile.Test.HelloTest> getHelloList() {
        if (helloBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hello_);
        } else {
          return helloBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public int getHelloCount() {
        if (helloBuilder_ == null) {
          return hello_.size();
        } else {
          return helloBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public com.compare.protobuffile.Test.HelloTest getHello(int index) {
        if (helloBuilder_ == null) {
          return hello_.get(index);
        } else {
          return helloBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder setHello(
          int index, com.compare.protobuffile.Test.HelloTest value) {
        if (helloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHelloIsMutable();
          hello_.set(index, value);
          onChanged();
        } else {
          helloBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder setHello(
          int index, com.compare.protobuffile.Test.HelloTest.Builder builderForValue) {
        if (helloBuilder_ == null) {
          ensureHelloIsMutable();
          hello_.set(index, builderForValue.build());
          onChanged();
        } else {
          helloBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder addHello(com.compare.protobuffile.Test.HelloTest value) {
        if (helloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHelloIsMutable();
          hello_.add(value);
          onChanged();
        } else {
          helloBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder addHello(
          int index, com.compare.protobuffile.Test.HelloTest value) {
        if (helloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHelloIsMutable();
          hello_.add(index, value);
          onChanged();
        } else {
          helloBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder addHello(
          com.compare.protobuffile.Test.HelloTest.Builder builderForValue) {
        if (helloBuilder_ == null) {
          ensureHelloIsMutable();
          hello_.add(builderForValue.build());
          onChanged();
        } else {
          helloBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder addHello(
          int index, com.compare.protobuffile.Test.HelloTest.Builder builderForValue) {
        if (helloBuilder_ == null) {
          ensureHelloIsMutable();
          hello_.add(index, builderForValue.build());
          onChanged();
        } else {
          helloBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder addAllHello(
          java.lang.Iterable<? extends com.compare.protobuffile.Test.HelloTest> values) {
        if (helloBuilder_ == null) {
          ensureHelloIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hello_);
          onChanged();
        } else {
          helloBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder clearHello() {
        if (helloBuilder_ == null) {
          hello_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          helloBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public Builder removeHello(int index) {
        if (helloBuilder_ == null) {
          ensureHelloIsMutable();
          hello_.remove(index);
          onChanged();
        } else {
          helloBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public com.compare.protobuffile.Test.HelloTest.Builder getHelloBuilder(
          int index) {
        return getHelloFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public com.compare.protobuffile.Test.HelloTestOrBuilder getHelloOrBuilder(
          int index) {
        if (helloBuilder_ == null) {
          return hello_.get(index);  } else {
          return helloBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public java.util.List<? extends com.compare.protobuffile.Test.HelloTestOrBuilder> 
           getHelloOrBuilderList() {
        if (helloBuilder_ != null) {
          return helloBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hello_);
        }
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public com.compare.protobuffile.Test.HelloTest.Builder addHelloBuilder() {
        return getHelloFieldBuilder().addBuilder(
            com.compare.protobuffile.Test.HelloTest.getDefaultInstance());
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public com.compare.protobuffile.Test.HelloTest.Builder addHelloBuilder(
          int index) {
        return getHelloFieldBuilder().addBuilder(
            index, com.compare.protobuffile.Test.HelloTest.getDefaultInstance());
      }
      /**
       * <code>repeated .com.compare.HelloTest hello = 1;</code>
       */
      public java.util.List<com.compare.protobuffile.Test.HelloTest.Builder> 
           getHelloBuilderList() {
        return getHelloFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.compare.protobuffile.Test.HelloTest, com.compare.protobuffile.Test.HelloTest.Builder, com.compare.protobuffile.Test.HelloTestOrBuilder> 
          getHelloFieldBuilder() {
        if (helloBuilder_ == null) {
          helloBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.compare.protobuffile.Test.HelloTest, com.compare.protobuffile.Test.HelloTest.Builder, com.compare.protobuffile.Test.HelloTestOrBuilder>(
                  hello_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          hello_ = null;
        }
        return helloBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.compare.HelloCon)
    }

    static {
      defaultInstance = new HelloCon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.compare.HelloCon)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_compare_HelloTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_compare_HelloTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_compare_HelloCon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_compare_HelloCon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021testcompare.proto\022\013com.compare\"L\n\tHell" +
      "oTest\022\n\n\002id\030\001 \002(\005\022\025\n\004name\030\002 \001(\t:\007default" +
      "\022\r\n\005speak\030\003 \001(\t\022\r\n\005phone\030\004 \003(\t\"1\n\010HelloC" +
      "on\022%\n\005hello\030\001 \003(\0132\026.com.compare.HelloTes" +
      "tB \n\030com.compare.protobuffileB\004Test"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_compare_HelloTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_compare_HelloTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_compare_HelloTest_descriptor,
        new java.lang.String[] { "Id", "Name", "Speak", "Phone", });
    internal_static_com_compare_HelloCon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_compare_HelloCon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_compare_HelloCon_descriptor,
        new java.lang.String[] { "Hello", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
